language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 6
  - 8
  - 10
after_success:
  - yarn build
  - which npx && npx travis-deploy-once "npx semantic-release@15"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
