language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 6
  - 8
  - 10
after_success:
  - yarn build && yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
